import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // We wrap the entire app in the ClerkProvider to enable the authentication. This is built in when we install Clerk.
    <ClerkProvider>
      <html lang="en">
        <body className="min-h-screen ">
          <Nav></Nav>
          <div className="flex flex-col items-center p-24">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
